defmodule Nexus.Repo.Migrations.AddTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :available_templates, {:array, :text},
        null: false,
        default: fragment("ARRAY['default']::text[]")
    end

    alter table(:pages) do
      add :template_slug, :text, null: false, default: "default"
    end

    # Add template_data column first, then migrate data, then drop content
    alter table(:page_versions) do
      add :template_data, :map
    end

    flush()

    # Wrap existing content into template_data as {"body": <content>}
    execute """
    UPDATE page_versions
    SET template_data = jsonb_build_object('body', content)
    WHERE content IS NOT NULL
    """

    execute """
    UPDATE page_versions
    SET template_data = '{"body": {"type": "doc", "content": [{"type": "paragraph"}]}}'::jsonb
    WHERE template_data IS NULL
    """

    alter table(:page_versions) do
      remove :content
    end
  end

  def down do
    alter table(:page_versions) do
      add :content, :map
    end

    flush()

    # Extract body from template_data back into content
    execute """
    UPDATE page_versions
    SET content = template_data->'body'
    WHERE template_data IS NOT NULL AND template_data ? 'body'
    """

    alter table(:page_versions) do
      remove :template_data
    end

    alter table(:pages) do
      remove :template_slug
    end

    alter table(:projects) do
      remove :available_templates
    end
  end
end
