defmodule Nexus.Repo.Migrations.AddHasUnpublishedChangesToPageLocales do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:page_locales) do
      add :has_unpublished_changes, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:page_locales) do
      remove :has_unpublished_changes
    end
  end
end
