defmodule Nexus.Repo.Migrations.ReplaceBlocksWithTiptapContent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:page_versions) do
      remove :blocks
      add :content, :map, default: %{"type" => "doc", "content" => []}
      add :content_html, :text
    end
  end

  def down do
    alter table(:page_versions) do
      remove :content_html
      remove :content
      add :blocks, {:array, :map}, default: []
    end
  end
end
