defmodule Nexus.Repo.Migrations.AddAvailableLocalesToProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :available_locales, {:array, :text}, null: false, default: ["en"]
    end
  end

  def down do
    alter table(:projects) do
      remove :available_locales
    end
  end
end
