defmodule Nexus.Repo.Migrations.AddSystemPromptToProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :system_prompt, :text
    end
  end

  def down do
    alter table(:projects) do
      remove :system_prompt
    end
  end
end
