defmodule Nexus.Repo.Migrations.RemovePageStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pages) do
      remove :published_at
      remove :status
    end
  end

  def down do
    alter table(:pages) do
      add :status, :text, null: false, default: "draft"
      add :published_at, :utc_datetime
    end
  end
end
