defmodule Nexus.Repo.Migrations.CreateProjectsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :citext, null: false
      add :description, :text
      add :is_public, :boolean, null: false, default: false
      add :default_locale, :text, null: false, default: "en"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:projects, [:slug], name: "projects_unique_slug_index")

    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "viewer"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "memberships_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:memberships, [:user_id, :project_id],
             name: "memberships_unique_user_project_index"
           )
  end

  def down do
    drop_if_exists unique_index(:memberships, [:user_id, :project_id],
                     name: "memberships_unique_user_project_index"
                   )

    drop constraint(:memberships, "memberships_project_id_fkey")

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop table(:memberships)

    drop_if_exists unique_index(:projects, [:slug], name: "projects_unique_slug_index")

    drop table(:projects)
  end
end
