defmodule Nexus.Repo.Migrations.CreateProjectApiKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:project_api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :key_hash, :binary, null: false
      add :key_prefix, :text, null: false
      add :scopes, {:array, :text}, null: false
      add :is_active, :boolean, null: false, default: true
      add :expires_at, :utc_datetime
      add :last_used_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "project_api_keys_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "project_api_keys_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:project_api_keys, [:key_hash],
             name: "project_api_keys_unique_key_hash_index"
           )
  end

  def down do
    drop_if_exists unique_index(:project_api_keys, [:key_hash],
                     name: "project_api_keys_unique_key_hash_index"
                   )

    drop constraint(:project_api_keys, "project_api_keys_project_id_fkey")

    drop constraint(:project_api_keys, "project_api_keys_created_by_id_fkey")

    drop table(:project_api_keys)
  end
end
