defmodule Nexus.Repo.Migrations.CreateContentDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :citext, null: false
      add :full_path, :citext, null: false
      add :status, :text, null: false, default: "draft"
      add :position, :bigint, null: false, default: 0
      add :published_at, :utc_datetime
      add :archived_at, :utc_datetime
      add :deleted_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "pages_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :directory_id, :uuid
      add :parent_page_id, :uuid
    end

    create table(:page_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_number, :bigint, null: false
      add :locale, :text, null: false, default: "en"
      add :title, :text
      add :meta_description, :text
      add :meta_keywords, {:array, :text}, default: []
      add :og_title, :text
      add :og_description, :text
      add :og_image_url, :text
      add :blocks, {:array, :map}, default: []
      add :is_current, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :page_id,
          references(:pages,
            column: :id,
            name: "page_versions_page_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "page_versions_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:page_versions, [:page_id, :locale, :version_number],
             name: "page_versions_unique_version_index"
           )

    create table(:page_locales, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :locale, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :page_id,
          references(:pages,
            column: :id,
            name: "page_locales_page_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :published_version_id,
          references(:page_versions,
            column: :id,
            name: "page_locales_published_version_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:page_locales, [:page_id, :locale],
             name: "page_locales_unique_locale_per_page_index"
           )

    create table(:directories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:pages) do
      modify :directory_id,
             references(:directories,
               column: :id,
               name: "pages_directory_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :parent_page_id,
             references(:pages,
               column: :id,
               name: "pages_parent_page_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:pages, [:full_path, :project_id],
             name: "pages_unique_path_per_project_index"
           )

    alter table(:directories) do
      add :name, :text, null: false
      add :slug, :citext, null: false
      add :full_path, :citext, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "directories_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :parent_id,
          references(:directories,
            column: :id,
            name: "directories_parent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:directories, [:full_path, :project_id],
             name: "directories_unique_path_per_project_index"
           )
  end

  def down do
    drop_if_exists unique_index(:directories, [:full_path, :project_id],
                     name: "directories_unique_path_per_project_index"
                   )

    drop constraint(:directories, "directories_project_id_fkey")

    drop constraint(:directories, "directories_parent_id_fkey")

    alter table(:directories) do
      remove :parent_id
      remove :project_id
      remove :updated_at
      remove :inserted_at
      remove :position
      remove :full_path
      remove :slug
      remove :name
    end

    drop_if_exists unique_index(:pages, [:full_path, :project_id],
                     name: "pages_unique_path_per_project_index"
                   )

    drop constraint(:pages, "pages_directory_id_fkey")

    drop constraint(:pages, "pages_parent_page_id_fkey")

    alter table(:pages) do
      modify :parent_page_id, :uuid
      modify :directory_id, :uuid
    end

    drop table(:directories)

    drop_if_exists unique_index(:page_locales, [:page_id, :locale],
                     name: "page_locales_unique_locale_per_page_index"
                   )

    drop constraint(:page_locales, "page_locales_page_id_fkey")

    drop constraint(:page_locales, "page_locales_published_version_id_fkey")

    drop table(:page_locales)

    drop_if_exists unique_index(:page_versions, [:page_id, :locale, :version_number],
                     name: "page_versions_unique_version_index"
                   )

    drop constraint(:page_versions, "page_versions_page_id_fkey")

    drop constraint(:page_versions, "page_versions_created_by_id_fkey")

    drop table(:page_versions)

    drop constraint(:pages, "pages_project_id_fkey")

    drop table(:pages)
  end
end
