defmodule Nexus.Repo.Migrations.AddPublishedAtToPageLocales do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:page_locales) do
      add :published_at, :utc_datetime
    end
  end

  def down do
    alter table(:page_locales) do
      remove :published_at
    end
  end
end
