defmodule Nexus.Repo.Migrations.AddMediaItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:media_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :filename, :text, null: false
      add :file_path, :text, null: false
      add :mime_type, :text, null: false
      add :file_size, :bigint, null: false
      add :width, :bigint
      add :height, :bigint
      add :alt_text, :text
      add :variants, :map, default: %{}
      add :storage_backend, :text, null: false
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "media_items_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :uploaded_by_id,
          references(:users,
            column: :id,
            name: "media_items_uploaded_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:media_items, "media_items_project_id_fkey")

    drop constraint(:media_items, "media_items_uploaded_by_id_fkey")

    drop table(:media_items)
  end
end
